name: Check PR source branch

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Verify PR source
        run: |
          if [ "${{ github.head_ref }}" != "develop" ]; then
            echo "PRs to main must come from develop"
            exit 1
          fi
